server:
  port: 9090
   
spring:
  application:
    name: springboot-with-multiple-datasource01

#Account DB    
  accountdb:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/account_db?createDatabaseIfNotExist=true
      username: root
      password: root
      
#User DB
  userdb:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
      username: root
      password: root
      
#Common Prop's
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
